export const ALLOWED_SUBURBS = [
  "Aanwins",
  "Allen's Nek",
  "Allen's Nek Extensions",
  "Alsef",
  "Alsef Ext.1",
  "Ambot",
  "Amorosa",
  "Amorosa Extensions",
  "Arena",
  "Ballindean",
  "Batavia",
  "Batavia Ext.1",
  "Bellairspark",
  "Bellairspark Extensions",
  "Bloubosrand Ext.13",
  "Boskruin",
  "Boskruin Extensions",
  "Boundary Park",
  "Boundary Park Extensions",
  "Bram Fischerville",
  "Bram Fischerville Extensions",
  "Breaunanda Ext.2",
  "Bromhof",
  "Bromhof Extensions",
  "Brushwood Haugh",
  "Bush Hill Estate Ext.1",
  "Carenvale",
  "Constantia Kloof",
  "Constantia Kloof Extensions",
  "Cosmo City",
  "Cosmo City Extensions",
  "Creswell Park",
  "Culembeeck",
  "Culembeeck Ext.1",
  "Davidsonville",
  "Davidsonville Ext.1 & 2",
  "Discovery",
  "Discovery Extensions",
  "Dobsonville Ext.8",
  "Doornkop Ext.2 & 3",
  "Douglasdale",
  "Douglasdale Extensions",
  "Fairland",
  "Fairland Extensions",
  "Fleurhof",
  "Floracliffe",
  "Floracliffe Ext.1",
  "Florida",
  "Florida Extensions",
  "Florida Hills",
  "Florida Hills Ext. 2 & 4",
  "Florida Lake",
  "Florida North",
  "Florida North Extensions",
  "Florida Park",
  "Florida Park Extensions",
  "Florida View",
  "Georginia",
  "Glen Dayson",
  "Golden Harvest",
  "Goudrand",
  "Goudrand Ext. 1 & 2",
  "Grobler Park Extensions",
  "Hamberg",
  "Harveston",
  "Haylon Hill",
  "Helderkruin",
  "Helderkruin Extensions",
  "Honey Hill",
  "Honey Park Ext.6",
  "Honeydew",
  "Honeydew Extensions",
  "Honeydew Grove",
  "Honeydew Grove Extensions",
  "Honeydew Manor",
  "Honeydew Manor Extensions",
  "Honeydew Ridge Extensions",
  "Hoogland",
  "Hoogland Extensions",
  "Horison",
  "Horison Ext.1",
  "Horison Park",
  "Horizon View",
  "Horizon View Extensions",
  "Hunters Hill",
  "Johannesburg-North",
  "Jukskei Park",
  "Jukskei Park Ext.1",
  "Jukskei Park Ext.5",
  "Kelly Ridge",
  "Kevin Ridge Ext.3",
  "Kevin Ridge Proper",
  "Kimbult",
  "Kloofendal",
  "Kloofendal Extensions",
  "Kya Sand Extensions",
  "Laser Park",
  "Laser Park Extensions",
  "Lea Glen",
  "Leratong Village",
  "Lindhaven",
  "Lindhaven Extensions",
  "Little Falls Extensions",
  "Manufacta",
  "Manufacta Extensions",
  "Matholesville",
  "Matholesville Ext.2",
  "Meadowhurst",
  "Meadowlands Extensions",
  "Mmesi Park",
  "Mostyn Park",
  "Noordekrans Ext.2",
  "Noordhang",
  "Noordhang Extensions",
  "North Riding",
  "North Riding Estates Ext.1",
  "North Riding Estates Proper",
  "North Riding Extensions",
  "Northcliff Extensions",
  "Northgate",
  "Northgate Extensions",
  "Northwold Ext.11 & 16",
  "Northwold Extensions",
  "Olivedale Extensions",
  "Ontdekkerspark",
  "Ontdekkerspark Ext.1",
  "Paarderand Ext.1",
  "Panorama",
  "Panorama Ext.1",
  "Pennyville",
  "Poortview",
  "Poortview Extensions",
  "Princess",
  "Princess Extensions",
  "Putcoton",
  "Quellerina Ext.4",
  "Radiokop",
  "Radiokop Extensions",
  "Rand Leases Extensions",
  "Randparkrif Extensions",
  "Reefhaven",
  "Robertville",
  "Robertville Extensions",
  "Roodekrans",
  "Roodekrans Extensions",
  "Roodepoort",
  "Roodepoort Ext.2",
  "Roodepoort North",
  "Roodepoort West",
  "Roodepoort West Extensions",
  "Ruimsig",
  "Ruimsig Extensions",
  "Sandpark",
  "Selwyn",
  "Sharonlea",
  "Sharonlea Extensions",
  "Sonnedal",
  "Sonneglans Extensions",
  "Stormill",
  "Stormill Extensions",
  "Strijdompark Ext.1 & 3",
  "Strubens Ridge",
  "Strubensvallei",
  "Strubensvallei Extensions",
  "Sundowner",
  "Sundowner Extensions",
  "Technikon",
  "Thulani",
  "Thulani Ext.1 & 2",
  "Tres Jolie",
  "Tres Jolie Extensions",
  "Tshepisong",
  "Weltevredenpark Extensions",
  "Westgate Park Ext.1 & 2",
  "Wibsey Dip",
  "Wilfordon",
  "Wilfordon Ext.1",
  "Wilgeheuwel",
  "Wilgeheuwel Extensions",
  "Willowbrook Extensions",
  "Wilropark",
  "Wilropark Extensions",
  "Witpoortjie",
  "Witpoortjie Extensions",
  "Zandspruit",
  "Zandspruit Extensions",
  "Zonnehoewe",
];

function normalizeSuburb(str) {
  return str
    .trim()
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/\bext\.\s*/gi, "ext ")
    .replace(/\s+/g, " ")
    .trim();
}

// Splits "X Ext.1 & 2" into ["X Ext.1", "X Ext.2"]
function expandEntry(name) {
  const m = name.match(/^(.*\bExt[.\s]*)(\d+)\s*&\s*(\d+)(.*)$/i);
  if (m) return [`${m[1]}${m[2]}${m[4]}`, `${m[1]}${m[3]}${m[4]}`];
  return [name];
}

const NORMALIZED_SET = new Set(
  ALLOWED_SUBURBS.flatMap(expandEntry).map(normalizeSuburb)
);

export function isAllowedSuburb(candidate) {
  if (!candidate) return false;
  return NORMALIZED_SET.has(normalizeSuburb(candidate));
}
